project: PT-training
group: PT
name: pt
embd_dim: 256
pref_attn_embd_dim: null
num_heads: 4
attn_dropout: 0.1
resid_dropout: 0.1
intermediate_dim: null
num_layers: 1
embd_dropout: 0.1
model_eps: 0.1
max_ep_length: null
default_max_pos: 2048
dataset_id: D4RL_antmaze-large-play-v2
dataset: data/antmaze/antmaze-large-play-v2_pref_nt.hdf5
training_split: 0.8
epochs: 10
batch_size: 256
lr: 0.0003
eval_every: 1
criteria_key: acc
pin_memory: true
seed: 0
checkpoints_path: ./exp/reward_learning/antmaze_large_play_pt