project: BB-training
group: BB
name: bb
width: 128
depth: 3
batch_size: 256
num_samples: 250
n_discarded: 0
num_burn_in_steps: 3000
keep_every: 1
sghmc_lr: 0.008
num_chains: 4
mdecay: 0.01
print_every_n_samples: 250
dataset: data/bb/t0012_pref.hdf5
dataset_id: bb_t0012
training_split: 0.8
seed: 0
OUT_DIR: ./exp/reward_learning/bb_FG