project: optim-training
group: optim
name: optim
width: 256
depth: 2
activations: relu
dataset_id: D4RL_antmaze-large-diverse-v2
dataset: data/antmaze/antmaze-large-diverse-v2_pref_nt.hdf5
training_split: 0.8
epochs: 10
batch_size: 256
lr: 0.0003
eval_every: 1
criteria_key: acc
pin_memory: true
seed: 0
checkpoints_path: ./exp/reward_learning/antmaze_large_diverse_optim
prior: ./exp/reward_learning/antmaze_tuning