project: MR-training
group: MR
name: mr
width: 8
depth: 2
activations: relu
dataset_id: D4RL_antmaze-large-play-v2
train_dataset: data/antmaze/antmaze-large-play-v2/eval/seed_1/antmaze-large-play-v2_pref_train_1.hdf5
val_dataset: data/antmaze/antmaze-large-play-v2/eval/seed_1/antmaze-large-play-v2_pref_val_1.hdf5
epochs: 10
batch_size: 64
lr: 0.0003
eval_every: 1
criteria_key: acc
compile_model: true
pin_memory: true
seed: 0
checkpoints_path: ./exp/reward_learning/antmaze_large_play_mr