project: BNN-training
group: BNN
name: bnn
width: 8
depth: 6
num_chains: 2
chains_per_gpu: 2
num_samples: 12
n_discarded: 0
num_burn_in_steps: 5000
sghmc_lr: 0.001412083692555041
mdecay: 0.09726028131296788
batch_size: 64
max_param_step: 0.5
n_meas: 10
meas_jitter: 1.0e-06
gp_cov_scale: 1.0
reward_function: antmaze_task_reward_prior
n_concepts: null
gp_prior_type: map_informed
map_size: medium
map_env_name: antmaze-medium-play-v2
map_eta: 1.0
map_sig_c2: 1.0
map_sig_g2: 1.0
map_sig_n2: 0.001
map_xy_source: obs
use_cyclical_lr: true
sghmc_lr_max: 0.0048
cycle_length: 1250
fraction_cool: 0.25
keep_every: 1000
antmaze_variant: antmaze-medium-play-v2
dataset_id: D4RL_antmaze-medium-play-v2
measurement_dataset: data/antmaze/antmaze-medium-play-v2/antmaze-medium-play-v2_tuning_set.hdf5
warmup_log_every: 0
early_stop_acc_threshold: 0.0
print_every_n_samples: 10
seed: 1
OUT_DIR: ./exp/_gradnorm_readout/mp_lrmax4800
