project: BR-training-optim
group: BR
name: br
width: 64
depth: 2
batch_size: 256
num_samples: 60
n_discarded: 10
num_burn_in_steps: 3000
keep_every: 2000
sghmc_lr: 0.008
num_chains: 4
mdecay: 0.01
print_every_n_samples: 5
dataset: data/antmaze/antmaze-medium-play-v2_pref.hdf5
dataset_id: antmaze_medium_play
training_split: 0.8
seed: 0
OUT_DIR: ./exp/reward_learning/antmaze_medium_play_optim
prior_dir: ./exp/reward_learning/antmaze_tuning
prior_ckpt: 1000