project: BR-training
group: BR
name: br
width: 64
depth: 3
tuning_set: data/antmaze/antmaze-medium-play-v2_tuning_set.hdf5
dataset_id: antmaze_medium_play
mapper_num_iters: 1000
n_data: 512
wasserstein_steps_0: 0
wasserstein_steps_1: 1200
n_samples: 1024
wasserstein_lr: 0.001
lr: 0.08
save_ckpt_every: 50
print_every: 20
seed: 0
OUT_DIR: ./exp/reward_learning/antmaze_tuning