project: BR-training-FG
group: BR
name: br
width: 64
depth: 4
batch_size: 256
num_samples: 60
n_discarded: 10
num_burn_in_steps: 3000
keep_every: 2000
sghmc_lr: 0.008
num_chains: 4
mdecay: 0.01
print_every_n_samples: 5
dataset: data/antmaze/antmaze-large-diverse-v2_pref.hdf5
dataset_id: D4RL_antmaze-large-diverse-v2
training_split: 0.8
seed: 0
OUT_DIR: ./exp/reward_learning/antmaze_large_diverse_FG