project: BR-training
group: BR
name: br
width: 64
depth: 3
batch_size: 256
num_samples: 60
n_discarded: 30
num_burn_in_steps: 5000
keep_every: 5000
sghmc_lr: 0.01
num_chains: 4
mdecay: 0.01
print_every_n_samples: 5
dataset: data/bb/t0012_pref.hdf5
dataset_id: bb_t0012
training_split: 0.8
seed: 1
OUT_DIR: ./exp/reward_learning_gp/bb_optim
prior_dir: ./exp/reward_learning_gp/bb_tuning/br-02336596