project: BR-tuning-bnn
group: BR
name: br
width: 64
depth: 3
tuning_set: data/bb/bb_tuning_set.hdf5
mapper_num_iters: 300
n_data: 512
batches: 10
lr: 0.08
save_ckpt_every: 50
print_every: 20
seed: 1
OUT_DIR: ./exp/reward_learning/bb_tuning_star
prior_dir: ./exp/reward_learning/bb_tuning_star/br-02336596
prior_ckpt: 300
bnn_dir: ./exp/reward_learning/bb_optim/br-bb_t0012-b8ced45f
weights_dir: sampled_weights_0000003
bnn_width: 64
bnn_depth: 3